---
title: "Make run summary plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(dplyr)
require(magrittr)
require(reshape2)
require(Matrix)
require(ggExtra)
options(stringsAsFactors = FALSE)
getwd()
```

# Configuration

```{r paths}
emb_path <- './runs/EX11_04/logs'
pheno_df_path <- "./dataset/10X_PBMC_V1_V3_V31_integrated/pheno.csv"
expr_mat_path <- "./dataset/10X_PBMC_V1_V3_V31_integrated/cleaned_log_unfiltered_expr_mat.mtx"
gene_name_path <- "./dataset/10X_PBMC_V1_V3_V31_integrated/cleaned_log_unfiltered_gene_names.csv"
cell_name_path <- "./dataset/10X_PBMC_V1_V3_V31_integrated/cleaned_log_unfiltered_cell_names.csv"
```

# Import Labels

```{r import labels}
pheno_df <- read.csv(pheno_df_path) %>%
    rename('cell' = 'X')
expr_mat <- readMM(expr_mat_path)
gene_names <- read.csv(gene_name_path)[, 2]
cell_names <- read.csv(cell_name_path)[, 2]
rownames(expr_mat) <- gene_names
colnames(expr_mat) <- cell_names
```

# Make Embedding Plots

```{r global configs}
epoch_list_long <- c(164, 331, 498, 664, 829, 997)
epoch_list_short <- c(164, 498, 997)
```

## Main latent plots (main.1 and main.2)


```{r main latent plots}
try({
        keys_to_plot <- c("merged_overall_train_all_latent")
        #keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
        #                  "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
        #                  "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
        output_width <- 15
        output_height <- 15
        # for (i in 8:total_epochs) {
        #for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (i in epoch_list_short) {
            for (cur_key in keys_to_plot) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df %>% select(cell, data_key, source), by = 'cell')

                plt <- ggplot(cur_emb) +
                    geom_point(aes(x = main.1, y = main.2, color = data_key, alpha = (source == 'v1_purified'))) +
                    scale_alpha_manual(limits = c(TRUE, FALSE), values = c(0.3, 1)) +
                    scale_color_brewer(palette = 'Paired') +
                    theme_classic() +
                    theme(legend.position = 'bottom')
                plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
                plt_path <- './runs/EX11_04/plots/main_lat'
                system(paste0('mkdir -p ', plt_path))
                plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_main.jpg')
                ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
            }
        }
    })
```

## Phenotype latents

```{r data_key distrib}
try({
        keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent")
        #keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
        #                  "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
        #                  "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
        output_width <- 15
        output_height <- 15
        # for (i in 7:total_epochs) {
        # for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (i in epoch_list_short) {
            for (cur_key in keys_to_plot) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df %>% select(cell, data_key, source), by = 'cell')
                plt <- ggplot(cur_emb) +
                    geom_point(aes(x = data_key.1, y = data_key.2, color = data_key, alpha = (source == 'v1_purified'))) +
                    scale_alpha_manual(limits = c(TRUE, FALSE), values = c(0.3, 1)) +
                    scale_color_brewer(palette = 'Paired') +
                    theme_classic() +
                    theme(legend.position = 'bottom')
                plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
                plt_path <- './runs/EX11_04/plots/data_key_distrib'
                system(paste0('mkdir -p ', plt_path))
                plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_data_key.jpg')
                ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
            }
        }
    })
```

```{r source distrib}
try({
        keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent")
        #keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
        #                  "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
        #                  "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
        output_width <- 5
        output_height <- 5
        # for (i in 7:total_epochs) {
        # for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (i in epoch_list_short) {
            for (cur_key in keys_to_plot) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df %>% select(cell, data_key, source), by = 'cell')
                plt <- ggplot(cur_emb) +
                    geom_density(aes(x = source.1, color = source)) +
                    scale_alpha_manual(limits = c(TRUE, FALSE), values = c(1, 0.3)) +
                    scale_color_brewer(palette = 'Paired') +
                    theme_classic() +
                    theme(legend.position = 'bottom')
                plt_path <- './runs/EX11_04/plots/source_distrib'
                system(paste0('mkdir -p ', plt_path))
                plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_source.jpg')
                ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
            }
        }
    })
```

## Signature

### Outside panel genes

```{r source distrib}
try({
        keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent")
        #keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
        #                  "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
        #                  "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
        output_width <- 15
        output_height <- 15
        # for (i in 7:total_epochs) {
        # for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (i in epoch_list_short) {
            for (cur_key in keys_to_plot) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df %>% select(cell, data_key, source), by = 'cell')
                plt <- ggplot(cur_emb) +
                    geom_point(aes(x = outside_panel.1, y = outside_panel.2, color = data_key, alpha = (source == 'v1_purified'))) +
                    scale_alpha_manual(limits = c(TRUE, FALSE), values = c(0.3, 1)) +
                    scale_color_brewer(palette = 'Paired') +
                    theme_classic() +
                    theme(legend.position = 'bottom')
                plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
                plt_path <- './runs/EX11_04/plots/outside_panel'
                system(paste0('mkdir -p ', plt_path))
                plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_outside_panel.jpg')
                ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
            }
        }
    })
```

## Protein marker

### Cell distribution in latent
```{r signature distrib}
try({
        keys_to_plot <- c("merged_overall_train_all_latent")
        #keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
        #                  "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
        #                  "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
        output_width <- 15
        output_height <- 15
        #for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (i in epoch_list_short) {
            for (cur_key in keys_to_plot) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df %>% select(cell, data_key), by = 'cell')
                plt <- ggplot(cur_emb) +
                    geom_point(aes(x = protein_markers.1, y = protein_markers.2, color = data_key, alpha = (data_key == 'V3_with_protein_barcode'))) +
                    scale_alpha_manual(limits = c(TRUE, FALSE), values = c(1, 0.3)) +
                    scale_color_brewer(palette = 'Paired') +
                    theme_classic() +
                    theme(legend.position = 'bottom')
                plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
                plt_path <- './runs/EX11_04/plots/protein_markers_distrib'
                system(paste0('mkdir -p ', plt_path))
                plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_protein_markers.jpg')
                ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
            }
        }
    })
```

### Individual protein markers

```{r}
try({
        keys_to_plot <- c("protein_v3_overall_train_all_latent")
        output_width <- 20
        output_height <- 20
        protein_marker_list <- c(
            "CD3.TotalSeqB",
            "CD4.TotalSeqB",
            "CD8a.TotalSeqB",
            "CD14.TotalSeqB",
            "CD15.TotalSeqB",
            "CD16.TotalSeqB",
            "CD56.TotalSeqB",
            "CD19.TotalSeqB",
            "CD25.TotalSeqB",
            "CD45RA.TotalSeqB",
            "CD45RO.TotalSeqB",
            "PD.1.TotalSeqB",
            "TIGIT.TotalSeqB",
            "CD127.TotalSeqB",
            "IgG2a.control.TotalSeqB",
            "IgG1.control.TotalSeqB",
            "IgG2b.control.TotalSeqB")

        pure_keys_list <- c("pure_v1_overall_train_all_latent")
        data_key_pure_to_inspect <- c("CD14+_Monocytes", "CD19+_B_Cells",
                                      "CD34+_Cells", "CD4+_CD25+_Regulatory_T_Cells",
                                      "CD4+_CD45RA+_CD25-_Naive_T_cells", "CD4+_CD45RO+_Memory_T_Cells",
                                      "CD4+_Helper_T_Cells", "CD56+_Natural_Killer_Cells",
                                      "CD8+_CD45RA+_Naive_Cytotoxic_T_Cells", "CD8+_Cytotoxic_T_cells")
        annot_df_path <- './dataset/10X_PBMC_V1_V3_V31_integrated/annot_df_all.csv'
        annot_df <- read.csv(annot_df_path) %>% select(-X)

        for (i in epoch_list_short) {
            for (key_idx in 1:length(keys_to_plot)) {
                cur_key <- keys_to_plot[key_idx]
                pure_key <- pure_keys_list[key_idx]
                pure_emb <- read.csv(paste0(emb_path, '/', i, '_', pure_key, '.csv')) %>%
                    left_join(y = pheno_df %>% select(cell, source, data_key), by = 'cell')
                for (cur_pure in data_key_pure_to_inspect) {
                    emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                    cur_emb <- read.csv(emb_filename) %>%
                        left_join(y = pheno_df, by = 'cell') %>%
                        left_join(y = annot_df, by = 'cell')

                    # Normalize protein marker abundance to [0,1] for each marker
                    for (cur_mkr in protein_marker_list) {
                        cur_emb[[cur_mkr]] <- 2^cur_emb[[cur_mkr]]
                        cur_emb[[cur_mkr]] <- cur_emb[[cur_mkr]] / max(cur_emb[[cur_mkr]])
                    }

                    molten_emb <- cur_emb %>%
                        melt(id.vars = c("cell", "main.1", "main.2", "data_key.1", "data_key.2", "protein_markers.1", "protein_markers.2", "source.1", "data_key", "source", "SingleR_immuneDB_main", "SingleR_immuneDB_fine", "SingleR_monaco_main", "SingleR_monaco_fine", "outside_panel.1", "outside_panel.2", "outside_panel.3", "outside_panel.4", "outside_panel.5", "outside_panel.6", "outside_panel.7"))

                    cur_pure_emb <- pure_emb %>% filter(data_key == cur_pure)

                    plt <- ggplot() +
                        theme_classic() +
                        ggtitle(paste('Epoch', i, cur_key, 'with', cur_pure)) +
                        geom_point(data = cur_pure_emb, aes(x = data_key.1, y = data_key.2), alpha = 0.1, color = 'grey') +
                        geom_point(data = molten_emb, aes(x = data_key.1, y = data_key.2, alpha = value, color = SingleR_monaco_main)) +
                        scale_color_brewer(palette = 'Set1') +
                        scale_alpha_continuous(range = c(0, 1)) +
                        facet_wrap(vars(variable))
                    plt_path <- './runs/EX11_04/plots/data_key_vs_protein_markers'
                    system(paste0('mkdir -p ', plt_path))
                    plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_', cur_pure, '.jpg')
                    ggsave(plt, filename = plt_filename, width = output_width, height = output_height)

                }
            }
        }

    })

```

```{r}
try({
        keys_to_plot <- c("protein_v3_overall_train_all_latent")
        output_width <- 20
        output_height <- 20
        protein_marker_list <- c(
            "CD3.TotalSeqB",
            "CD4.TotalSeqB",
            "CD8a.TotalSeqB",
            "CD14.TotalSeqB",
            "CD15.TotalSeqB",
            "CD16.TotalSeqB",
            "CD56.TotalSeqB",
            "CD19.TotalSeqB",
            "CD25.TotalSeqB",
            "CD45RA.TotalSeqB",
            "CD45RO.TotalSeqB",
            "PD.1.TotalSeqB",
            "TIGIT.TotalSeqB",
            "CD127.TotalSeqB",
            "IgG2a.control.TotalSeqB",
            "IgG1.control.TotalSeqB",
            "IgG2b.control.TotalSeqB")

        pure_keys_list <- c("pure_v1_overall_train_all_latent")
        data_key_pure_to_inspect <- c("CD14+_Monocytes", "CD19+_B_Cells",
                                      "CD34+_Cells", "CD4+_CD25+_Regulatory_T_Cells",
                                      "CD4+_CD45RA+_CD25-_Naive_T_cells", "CD4+_CD45RO+_Memory_T_Cells",
                                      "CD4+_Helper_T_Cells", "CD56+_Natural_Killer_Cells",
                                      "CD8+_CD45RA+_Naive_Cytotoxic_T_Cells", "CD8+_Cytotoxic_T_cells")
        annot_df_path <- './dataset/10X_PBMC_V1_V3_V31_integrated/annot_df_all.csv'
        annot_df <- read.csv(annot_df_path) %>% select(-X)

        for (i in epoch_list_short) {
            for (key_idx in 1:length(keys_to_plot)) {
                cur_key <- keys_to_plot[key_idx]
                pure_key <- pure_keys_list[key_idx]
                pure_emb <- read.csv(paste0(emb_path, '/', i, '_', pure_key, '.csv')) %>%
                    left_join(y = pheno_df %>% select(cell, source, data_key), by = 'cell')
                for (cur_pure in data_key_pure_to_inspect) {
                    emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                    cur_emb <- read.csv(emb_filename) %>%
                        left_join(y = pheno_df, by = 'cell') %>%
                        left_join(y = annot_df, by = 'cell')

                    # Normalize protein marker abundance to [0,1] for each marker
                    for (cur_mkr in protein_marker_list) {
                        cur_emb[[cur_mkr]] <- 2^cur_emb[[cur_mkr]]
                        cur_emb[[cur_mkr]] <- cur_emb[[cur_mkr]] / max(cur_emb[[cur_mkr]])
                    }

                    molten_emb <- cur_emb %>%
                        melt(id.vars = c("cell", "main.1", "main.2", "data_key.1", "data_key.2", "protein_markers.1", "protein_markers.2", "source.1", "data_key", "source", "SingleR_immuneDB_main", "SingleR_immuneDB_fine", "SingleR_monaco_main", "SingleR_monaco_fine", "outside_panel.1", "outside_panel.2", "outside_panel.3", "outside_panel.4", "outside_panel.5", "outside_panel.6", "outside_panel.7"))

                    cur_pure_emb <- pure_emb %>% filter(data_key == cur_pure)

                    plt <- ggplot() +
                        theme_classic() +
                        ggtitle(paste('Epoch', i, cur_key, 'with', cur_pure)) +
                        geom_point(data = cur_pure_emb, aes(x = protein_markers.1, y = protein_markers.2), alpha = 0.1, color = 'grey') +
                        geom_point(data = molten_emb, aes(x = protein_markers.1, y = protein_markers.2, alpha = value, color = SingleR_monaco_main)) +
                        scale_color_brewer(palette = 'Set1') +
                        scale_alpha_continuous(range = c(0, 1)) +
                        facet_wrap(vars(variable))
                    plt_path <- './runs/EX11_04/plots/protein_markers_vs_protein_markers'
                    system(paste0('mkdir -p ', plt_path))
                    plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_', cur_pure, '.jpg')
                    ggsave(plt, filename = plt_filename, width = output_width, height = output_height)

                }
            }
        }

    })

```
```{r}
try({
        keys_to_plot <- c("protein_v3_overall_train_all_latent")
        output_width <- 20
        output_height <- 20
        protein_marker_list <- c(
            "CD3.TotalSeqB",
            "CD4.TotalSeqB",
            "CD8a.TotalSeqB",
            "CD14.TotalSeqB",
            "CD15.TotalSeqB",
            "CD16.TotalSeqB",
            "CD56.TotalSeqB",
            "CD19.TotalSeqB",
            "CD25.TotalSeqB",
            "CD45RA.TotalSeqB",
            "CD45RO.TotalSeqB",
            "PD.1.TotalSeqB",
            "TIGIT.TotalSeqB",
            "CD127.TotalSeqB",
            "IgG2a.control.TotalSeqB",
            "IgG1.control.TotalSeqB",
            "IgG2b.control.TotalSeqB")

        pure_keys_list <- c("pure_v1_overall_train_all_latent")
        data_key_pure_to_inspect <- c("CD14+_Monocytes", "CD19+_B_Cells",
                                      "CD34+_Cells", "CD4+_CD25+_Regulatory_T_Cells",
                                      "CD4+_CD45RA+_CD25-_Naive_T_cells", "CD4+_CD45RO+_Memory_T_Cells",
                                      "CD4+_Helper_T_Cells", "CD56+_Natural_Killer_Cells",
                                      "CD8+_CD45RA+_Naive_Cytotoxic_T_Cells", "CD8+_Cytotoxic_T_cells")
        annot_df_path <- './dataset/10X_PBMC_V1_V3_V31_integrated/annot_df_all.csv'
        annot_df <- read.csv(annot_df_path) %>% select(-X)

        for (i in epoch_list_short) {
            for (key_idx in 1:length(keys_to_plot)) {
                cur_key <- keys_to_plot[key_idx]
                pure_key <- pure_keys_list[key_idx]
                pure_emb <- read.csv(paste0(emb_path, '/', i, '_', pure_key, '.csv')) %>%
                    left_join(y = pheno_df %>% select(cell, source, data_key), by = 'cell')
                for (cur_pure in data_key_pure_to_inspect) {
                    emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                    cur_emb <- read.csv(emb_filename) %>%
                        left_join(y = pheno_df, by = 'cell') %>%
                        left_join(y = annot_df, by = 'cell')

                    # Normalize protein marker abundance to [0,1] for each marker
                    for (cur_mkr in protein_marker_list) {
                        cur_emb[[cur_mkr]] <- 2^cur_emb[[cur_mkr]]
                        cur_emb[[cur_mkr]] <- cur_emb[[cur_mkr]] / max(cur_emb[[cur_mkr]])
                    }

                    molten_emb <- cur_emb %>%
                        melt(id.vars = c("cell", "main.1", "main.2", "data_key.1", "data_key.2", "protein_markers.1", "protein_markers.2", "source.1", "data_key", "source", "SingleR_immuneDB_main", "SingleR_immuneDB_fine", "SingleR_monaco_main", "SingleR_monaco_fine", "outside_panel.1", "outside_panel.2", "outside_panel.3", "outside_panel.4", "outside_panel.5", "outside_panel.6", "outside_panel.7"))

                    cur_pure_emb <- pure_emb %>% filter(data_key == cur_pure)

                    plt <- ggplot() +
                        theme_classic() +
                        ggtitle(paste('Epoch', i, cur_key, 'with', cur_pure)) +
                        geom_point(data = cur_pure_emb, aes(x = main.1, y = main.2), alpha = 0.1, color = 'grey') +
                        geom_point(data = molten_emb, aes(x = main.1, y = main.2, alpha = value, color = SingleR_monaco_main)) +
                        scale_color_brewer(palette = 'Set1') +
                        scale_alpha_continuous(range = c(0, 1)) +
                        facet_wrap(vars(variable))
                    plt_path <- './runs/EX11_04/plots/main_vs_protein_markers'
                    system(paste0('mkdir -p ', plt_path))
                    plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_', cur_pure, '.jpg')
                    ggsave(plt, filename = plt_filename, width = output_width, height = output_height)

                }
            }
        }

    })

```
## Mixture of V3 and V31 cells


```{r}
try({
        keys_to_inspect <- c('protein_v3_overall_train_all_latent', 'targeted_v31_overall_train_all_latent')
        output_width <- 20
        output_height <- 20

        # Cell type annotations
        annot_df_path <- './dataset/10X_PBMC_V1_V3_V31_integrated/annot_df_all.csv'
        annot_df <- read.csv(annot_df_path) %>% select(-X)

        for (i in epoch_list_short) {
            # Load embeddings
            combined_key <- ''
            combined_emb <- NULL
            for (cur_key in keys_to_inspect) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df, by = 'cell') %>%
                    left_join(y = annot_df, by = 'cell')
                combined_emb <- combined_emb %>% rbind(cur_emb)
                combined_key <- combined_key %>% paste0(., '_', cur_key)
            }

            plt <- ggplot() +
                theme_classic() +
                ggtitle(paste('Epoch', i, combined_key)) +
                geom_density(data = combined_emb, aes(x = source.1, color = source)) +
                scale_color_brewer(palette = 'Set1') +
                scale_alpha_continuous(range = c(0, 1)) +
                facet_wrap(vars(SingleR_monaco_main))
            plt_path <- './runs/EX11_04/plots/cell_mixture'
            system(paste0('mkdir -p ', plt_path))
            plt_filename <- paste0(plt_path, '/', i, '_', combined_key, '_source.jpg')
            ggsave(plt, filename = plt_filename, width = output_width, height = output_height)

            plt <- ggplot() +
                theme_classic() +
                ggtitle(paste('Epoch', i, combined_key)) +
                geom_point(data = combined_emb, aes(x = protein_markers.1, y = protein_markers.2, color = source), alpha = 0.5) +
                scale_color_brewer(palette = 'Set1') +
                scale_alpha_continuous(range = c(0, 1)) +
                facet_wrap(vars(SingleR_monaco_main))
            plt_path <- './runs/EX11_04/plots/cell_mixture'
            system(paste0('mkdir -p ', plt_path))
            plt_filename <- paste0(plt_path, '/', i, '_', combined_key, '_protein_markers.jpg')
            ggsave(plt, filename = plt_filename, width = output_width, height = output_height)

            plt <- ggplot() +
                theme_classic() +
                ggtitle(paste('Epoch', i, combined_key)) +
                geom_point(data = combined_emb, aes(x = main.1, y = main.2, color = source), alpha = 0.5) +
                scale_color_brewer(palette = 'Set1') +
                scale_alpha_continuous(range = c(0, 1)) +
                facet_wrap(vars(SingleR_monaco_main))
            plt_path <- './runs/EX11_04/plots/cell_mixture'
            system(paste0('mkdir -p ', plt_path))
            plt_filename <- paste0(plt_path, '/', i, '_', combined_key, '_main.jpg')
            ggsave(plt, filename = plt_filename, width = output_width, height = output_height)

            plt <- ggplot() +
                theme_classic() +
                ggtitle(paste('Epoch', i, combined_key)) +
                geom_point(data = combined_emb, aes(x = data_key.1, y = data_key.2, color = source), alpha = 0.5) +
                scale_color_brewer(palette = 'Set1') +
                scale_alpha_continuous(range = c(0, 1)) +
                facet_wrap(vars(SingleR_monaco_main))
            plt_path <- './runs/EX11_04/plots/cell_mixture'
            system(paste0('mkdir -p ', plt_path))
            plt_filename <- paste0(plt_path, '/', i, '_', combined_key, '_data_key.jpg')
            ggsave(plt, filename = plt_filename, width = output_width, height = output_height)


        }
    })
```


## 3-D Plots

```{r}
require(plotly)
require(htmlwidgets)
try({
        keys_to_plot <- c("merged_overall_train_all_latent")
        for (i in epoch_list_short) {
            for (cur_key in keys_to_plot) {
                emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
                cur_emb <- cur_emb <- read.csv(emb_filename) %>%
                    left_join(y = pheno_df, by = 'cell') %>%
                    left_join(y = annot_df, by = 'cell')
                plt <- plot_ly(cur_emb, x = ~protein_markers.1, y = ~protein_markers.2, z = ~source.1, color = ~data_key)
                plt_path <- paste0(getwd(), '/runs/EX11_04/plots/3d_plt/', i, '_protein_markers_source_', cur_key)
                system(paste0('mkdir -p ', plt_path))
                plt_filename <- paste0(plt_path, '/plt.html')
                saveWidget(plt, file = plt_filename)
            }
        }
    })

```

# Notes

