---
title: "Make run summary plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(dplyr)
require(magrittr)
require(reshape2)
require(Matrix)
require(ggExtra)
options(stringsAsFactors = FALSE)
getwd()
```

# Configuration

```{r paths}
emb_path <- './runs/EX07_05/logs'
pheno_df_path <- './dataset/10X_Purified_PBMC/pooled_pheno.csv'
expr_mat_path <- './dataset/10X_Purified_PBMC/cleaned_pooled_log_count_dgC_unfiltered.mtx'
gene_name_path <- './dataset/10X_Purified_PBMC/cleaned_pooled_log_count_dgC_unfiltered_gene_names.csv'
cell_name_path <- './dataset/10X_Purified_PBMC/cleaned_pooled_log_count_dgC_unfiltered_cell_names.csv'
```

# Import Labels

```{r import labels}
pheno_df <- read.csv(pheno_df_path) %>%
  rename('cell' = 'X')
expr_mat <- readMM(expr_mat_path)
gene_names <- read.csv(gene_name_path)[, 2]
cell_names <- read.csv(cell_name_path)[, 2]
rownames(expr_mat) <- gene_names
colnames(expr_mat) <- cell_names
```

# Make Embedding Plots

```{r global configs}
total_epochs <- 100
```

## Main latent plots (main.1 and main.2)


```{r signature latent plots}
try({
      keys_to_plot <- c("overall_train_all_latent", "overall_test_all_latent")
      output_width <- 15
      output_height <- 15
      for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (cur_key in keys_to_plot) {
          emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
          cur_emb <- read.csv(emb_filename) %>%
            left_join(y = pheno_df %>% select(cell, data_key), by = 'cell')

          plt <- ggplot(cur_emb) +
            geom_point(aes(x = main.1, y = main.2, color = data_key)) +
            theme_classic() +
            theme(legend.position = 'bottom')
          plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
          plt_path <- './runs/EX07_05/plots/main_lat'
          system(paste0('mkdir -p ', plt_path))
          plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_main.jpg')
          ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
        }
      }
    })
```


# Notes

## Observations



## Console outputs (initial part)

```
/Users/hahaschool/Desktop/Research/SAKRA/venv/bin/python "/Volumes/Macintosh HD/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py" --mode=client --port=59915
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Users/hahaschool/Desktop/Research/SAKRA'])
PyDev console: starting.
Python 3.7.8 (default, Jul  4 2020, 10:17:17)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
runfile('/Users/hahaschool/Desktop/Research/SAKRA/SAKRA.py', args=['--config', './runs/EX07_05/config.json', '--verbose', 'True'], wdir='/Users/hahaschool/Desktop/Research/SAKRA')
SCARE/SAKRA Prototype
Loading dataset...
Reproducibe seed: 114514
Loading expression matrix from mtx (MM) file.
==========================
rna_count dataset (sparse MM version):
Imported gene expression matrix from: ./dataset/10X_Purified_PBMC/cleaned_pooled_log_count_dgC_unfiltered.mtx
Imported gene names from: ./dataset/10X_Purified_PBMC/cleaned_pooled_log_count_dgC_unfiltered_gene_names.csv
Imported cell names from: ./dataset/10X_Purified_PBMC/cleaned_pooled_log_count_dgC_unfiltered_cell_names.csv
(19705, 94655)
cell     CD14+_Monocytes-AAACATACCACTAG-1  ...  CD14+_Monocytes-AAACATTGACGGTT-1
gene                                       ...
FAM138A                          0.000000  ...                          0.000000
OR4F5                            0.000000  ...                          0.000000
OR4F29                           0.000000  ...                          0.000000
OR4F16                           0.000000  ...                          0.000000
FAM87B                           0.000000  ...                          0.000000
                                   ...  ...                               ...
MT-ND4L                          0.000000  ...                          0.000000
MT-ND4                           2.807975  ...                          0.000000
MT-ND5                           0.000000  ...                          0.000000
MT-ND6                           0.000000  ...                          0.000000
MT-CYB                           0.000000  ...                          2.709732
[19705 rows x 3 columns]
No external gene expression set provided, using dummy.
Gene expression set metadata:
{'all': {'gene_list': '*', 'pre_procedure': [], 'post_procedure': [{'type': 'ToTensor'}]}}
Phenotype data from CSV from: ./dataset/10X_Purified_PBMC/pooled_pheno.csv
(94655, 1)
                                                       data_key
CD14+_Monocytes-AAACATACCACTAG-1                CD14+_Monocytes
CD14+_Monocytes-AAACATACGTTCAG-1                CD14+_Monocytes
CD14+_Monocytes-AAACATTGACGGTT-1                CD14+_Monocytes
CD14+_Monocytes-AAACATTGCTTCGC-1                CD14+_Monocytes
CD14+_Monocytes-AAACATTGGGCAAG-1                CD14+_Monocytes
                                                         ...
CD8+_Cytotoxic_T_cells-TTTGCATGAACGGG-1  CD8+_Cytotoxic_T_cells
CD8+_Cytotoxic_T_cells-TTTGCATGAAGATG-1  CD8+_Cytotoxic_T_cells
CD8+_Cytotoxic_T_cells-TTTGCATGAGCGTT-1  CD8+_Cytotoxic_T_cells
CD8+_Cytotoxic_T_cells-TTTGCATGCAAGCT-1  CD8+_Cytotoxic_T_cells
CD8+_Cytotoxic_T_cells-TTTGCATGCCGCTT-1  CD8+_Cytotoxic_T_cells
[94655 rows x 1 columns]
==========================
Configuration integrity pre-check ok: True
==========================
Splits:
{'all': array([ True,  True,  True, ...,  True,  True,  True]), 'overall_train': array([ True,  True, False, ...,  True,  True,  True]), 'overall_test': array([False, False,  True, ..., False, False, False])}
Model built:
ModuleDict(
  (decoder): FCDecoder(
    (model_list): ModuleList(
      (0): Linear(in_features=2, out_features=50, bias=True)
      (1): CELU(alpha=1.0)
      (2): Linear(in_features=50, out_features=50, bias=True)
      (3): CELU(alpha=1.0)
      (4): Linear(in_features=50, out_features=19705, bias=True)
    )
  )
  (main_latent_compressor): FCCompressor(
    (model_list): ModuleList(
      (0): Linear(in_features=50, out_features=2, bias=True)
    )
    (model): Sequential(
      (0): ModuleList(
        (0): Linear(in_features=50, out_features=2, bias=True)
      )
    )
  )
  (pheno_latent_compressors): ModuleDict()
  (pheno_models): ModuleDict()
  (pre_encoder): FCPreEncoder(
    (model_list): ModuleList(
      (0): Linear(in_features=19705, out_features=50, bias=True)
      (1): CELU(alpha=1.0)
      (2): Linear(in_features=50, out_features=50, bias=True)
      (3): CELU(alpha=1.0)
    )
  )
  (signature_latent_compressors): ModuleDict()
  (signature_regressors): ModuleDict()
)
===========================
Extractor controller
{}
{}
{'encoder_neurons': 50, 'decoder_neurons': 50, 'latent_dim': 2, 'loss': {'L2': {'type': 'MSE', 'init_weight': 1.0, 'progressive_const': 1.0, 'progressive_start_epoch': 100}, 'L1': {'type': 'L1', 'init_weight': 1.0, 'progressive_const': 1.0, 'progressive_start_epoch': 100}}, 'regularization': {}}
RMSprop (
Parameter Group 0
    alpha: 0.9
    centered: False
    eps: 1e-08
    lr: 0.001
    momentum: 0
    weight_decay: 0
)
      main_loss_L2    main_loss_L1
--  --------------  --------------
 0               1               1
 1               1               1
 2               1               1
 3               1               1
 4               1               1
 5               1               1
 6               1               1
 7               1               1
 8               1               1
 9               1               1
10               1               1
11               1               1
12               1               1
13               1               1
14               1               1
15               1               1
16               1               1
17               1               1
18               1               1
19               1               1
20               1               1
21               1               1
22               1               1
23               1               1
24               1               1
25               1               1
26               1               1
27               1               1
28               1               1
29               1               1
30               1               1
31               1               1
32               1               1
33               1               1
34               1               1
35               1               1
36               1               1
37               1               1
38               1               1
39               1               1
40               1               1
41               1               1
42               1               1
43               1               1
44               1               1
45               1               1
46               1               1
47               1               1
48               1               1
49               1               1
50               1               1
51               1               1
52               1               1
53               1               1
54               1               1
55               1               1
56               1               1
57               1               1
58               1               1
59               1               1
60               1               1
61               1               1
62               1               1
63               1               1
64               1               1
65               1               1
66               1               1
67               1               1
68               1               1
69               1               1
70               1               1
71               1               1
72               1               1
73               1               1
74               1               1
75               1               1
76               1               1
77               1               1
78               1               1
79               1               1
80               1               1
81               1               1
82               1               1
83               1               1
84               1               1
85               1               1
86               1               1
87               1               1
88               1               1
89               1               1
90               1               1
91               1               1
92               1               1
93               1               1
94               1               1
95               1               1
96               1               1
97               1               1
98               1               1
99               1               1
===========================



```