---
title: "Make run summary plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggplot2)
require(dplyr)
require(magrittr)
require(reshape2)
require(Matrix)
require(ggExtra)
require(RColorBrewer)
options(stringsAsFactors = FALSE)
getwd()
```

# Configuration

```{r paths}
emb_path <- './runs/EX08_01/logs'
pheno_df_path <- "./dataset/10X_PBMC_integrated_purified_and_cite/pheno.csv"
expr_mat_path <- "./dataset/10X_PBMC_integrated_purified_and_cite/cleaned_log_unfiltered_expr_mat.mtx"
gene_name_path <- "./dataset/10X_PBMC_integrated_purified_and_cite/cleaned_log_unfiltered_gene_names.csv"
cell_name_path <- "./dataset/10X_PBMC_integrated_purified_and_cite/cleaned_log_unfiltered_cell_names.csv"
```

# Import Labels

```{r import labels}
pheno_df <- read.csv(pheno_df_path) %>%
  rename('cell' = 'X')
expr_mat <- readMM(expr_mat_path)
gene_names <- read.csv(gene_name_path)[, 2]
cell_names <- read.csv(cell_name_path)[, 2]
rownames(expr_mat) <- gene_names
colnames(expr_mat) <- cell_names
```

# Make Embedding Plots

```{r global configs}
total_epochs <- 100
```

## Main latent plots (main.1 and main.2)


```{r signature latent plots}
try({
      keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
                        "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
                        "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
      output_width <- 15
      output_height <- 15
      for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (cur_key in keys_to_plot) {
          emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
          cur_emb <- read.csv(emb_filename) %>%
            left_join(y = pheno_df %>% select(cell, data_key), by = 'cell')

          plt <- ggplot(cur_emb) +
            geom_point(aes(x = main.1, y = main.2, color = data_key)) +
            theme_classic() +
            theme(legend.position = 'bottom')
          plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
          plt_path <- './runs/EX08_01/plots/main_lat'
          system(paste0('mkdir -p ', plt_path))
          plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_main.jpg')
          ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
        }
      }
    })
```

## Phenotype latents

```{r signature distrib}
try({
      keys_to_plot <- c("merged_overall_test_all_latent")
      #keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent",
      #                  "pure_v1_overall_train_all_latent", "pure_v1_overall_test_all_latent",
      #                  "protein_v3_overall_train_all_latent", "protein_v3_overall_test_all_latent")
      output_width <- 15
      output_height <- 15
      #for (i in c(seq(1, total_epochs, 9), total_epochs)) {
      for (i in seq(5, 100, 5)) {
        for (cur_key in keys_to_plot) {
          emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
          cur_emb <- read.csv(emb_filename) %>%
            left_join(y = pheno_df %>% select(cell, data_key), by = 'cell')
          plt <- ggplot(cur_emb) +
            geom_point(aes(x = data_key.1, y = data_key.2, color = data_key, alpha = (data_key == 'V3_with_protein_barcode'))) +
            scale_alpha_manual(limits = c(TRUE, FALSE), values = c(1, 0.3)) +
            scale_color_brewer(palette = 'Paired') +
            theme_classic() +
            theme(legend.position = 'bottom')
          plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
          plt_path <- './runs/EX08_01/plots/data_key_distrib'
          system(paste0('mkdir -p ', plt_path))
          plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_data_key.jpg')
          ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
        }
      }
    })
```

## Protein marker

### Cell distribution in latent
```{r signature distrib}
try({
      keys_to_plot <- c("merged_overall_train_all_latent", "merged_overall_test_all_latent")
      output_width <- 15
      output_height <- 15
      for (i in seq(5, total_epochs, 5)) {
        # for (i in 90:100) {
        for (cur_key in keys_to_plot) {
          emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
          cur_emb <- read.csv(emb_filename) %>%
            left_join(y = pheno_df %>% select(cell, data_key), by = 'cell')
          plt <- ggplot(cur_emb) +
            geom_point(aes(x = protein_markers.1, y = protein_markers.2, color = data_key, alpha = (data_key == 'V3_with_protein_barcode'))) +
            scale_alpha_manual(limits = c(TRUE, FALSE), values = c(1, 0.3)) +
            scale_color_brewer(palette = 'Paired') +
            theme_classic() +
            theme(legend.position = 'bottom')
          plt <- ggMarginal(plt, groupColour = TRUE, groupFill = TRUE)
          plt_path <- './runs/EX08_01/plots/protein_markers_distrib'
          system(paste0('mkdir -p ', plt_path))
          plt_filename <- paste0(plt_path, '/', i, '_', cur_key, '_protein_markers.jpg')
          ggsave(plt, filename = plt_filename, width = output_width, height = output_height)
        }
      }
    })
```

### Protein marker



## 3-D Plots

```{r}
require(plotly)
require(htmlwidgets)
try({
      keys_to_plot <- c("overall_train_all_latent", "overall_test_all_latent")
      for (i in c(seq(1, total_epochs, 9), total_epochs)) {
        for (cur_key in keys_to_plot) {
          emb_filename <- paste0(emb_path, '/', i, '_', cur_key, '.csv')
          cur_emb <- read.csv(emb_filename) %>%
            left_join(y = pheno_df %>% select(cell, data_key), by = 'cell')
          plt <- plot_ly(cur_emb, x = ~main.1, y = ~main.2, z = ~data_key.1, color = ~data_key)
          plt_path <- paste0(getwd(), '/runs/EX08_01/plots/3d_plt/', i, '_main.1_main.2_data_key_', cur_key)
          system(paste0('mkdir -p ', plt_path))
          plt_filename <- paste0(plt_path, '/plt.html')
          saveWidget(plt, file = plt_filename)
        }
      }
    })

```

# Notes

